name: tagsonomy
description: "Tagsonomy - RDF-based taxonomy and metadata management application"

command:
  - gunicorn
  - app:app
  - -w
  - 4

env:
  - name: FLASK_ENV
    value: production
  - name: SYNC_JOB_ID
    valueFrom: sync-tags-job